import { Link, useLocation } from "react-router-dom";

function ResultPage() {
const location = useLocation();

const predictedPrice = location.state?.predictedPrice;

if (predictedPrice === undefined) {
return (
<main className="result-page">
<section className="result-card empty-result">
<div className="result-icon">!</div>

      <p className="result-label">PREDICTION RESULT</p>

      <h1>No prediction found</h1>

      <p className="result-description">
        We couldn't find a prediction to display. Please go back and
        enter your property details first.
      </p>

      <Link className="result-button" to="/">
        Back to prediction
      </Link>
    </section>
  </main>
);

}

return (
<main className="result-page">
<section className="result-card">
<div className="success-icon">✓</div>

    <p className="result-label">YOUR ESTIMATED PRICE</p>

    <h1>Prediction Result</h1>

    <p className="result-description">
      Based on the property details you provided, the estimated price is:
    </p>

    <div className="price-box">
      <span>₹</span>
      <strong>
        {Number(predictedPrice).toLocaleString("en-IN", {
          maximumFractionDigits: 2,
        })}
      </strong>
    </div>

    <p className="result-note">
      This is an estimated value generated by the machine learning model.
    </p>

    <Link className="result-button" to="/">
      Make another prediction
    </Link>
  </section>
</main>

);
}

export default ResultPage;